# Agent Harness Framework - Project Initialization Script
# This script is generated by the Initializer agent and customized per project

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "  Agent Harness Framework - Init Script" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# Check if this is a fresh project
if (-not (Test-Path "memory/feature_list.json")) {
    Write-Host "⚠️  No feature_list.json found." -ForegroundColor Yellow
    Write-Host "   Run @Initializer first to set up the project."
    exit 1
}

# Display progress
Write-Host "📊 Current Progress:" -ForegroundColor Green
$featureList = Get-Content "memory/feature_list.json" | ConvertFrom-Json
$total = $featureList.features.Count
$passing = ($featureList.features | Where-Object { $_.passes -eq $true }).Count
Write-Host "   Features: $passing / $total passing"
Write-Host ""

# Project-specific setup goes here
# Uncomment and customize based on your project type:

# --- Node.js Project ---
# if (Test-Path "package.json") {
#     Write-Host "📦 Installing Node.js dependencies..." -ForegroundColor Blue
#     npm install
#     Write-Host ""
#     Write-Host "🚀 Starting development server..." -ForegroundColor Blue
#     Start-Process npm -ArgumentList "run", "dev" -NoNewWindow
#     Write-Host "   Server starting at http://localhost:3000"
# }

# --- Python Project ---
# if (Test-Path "requirements.txt") {
#     Write-Host "🐍 Installing Python dependencies..." -ForegroundColor Blue
#     pip install -r requirements.txt
#     Write-Host ""
#     Write-Host "🚀 Starting application..." -ForegroundColor Blue
#     Start-Process python -ArgumentList "app.py" -NoNewWindow
# }

# --- Docker Project ---
# if (Test-Path "docker-compose.yml") {
#     Write-Host "🐳 Starting Docker containers..." -ForegroundColor Blue
#     docker-compose up -d
# }

Write-Host "✅ Init complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Use @Coder to implement features"
Write-Host "  2. Check memory/claude-progress.md for context"
Write-Host "  3. Run 'git log --oneline -10' to see recent changes"
