#!/bin/bash
# Agent Harness Framework - Project Initialization Script
# This script is generated by the Initializer agent and customized per project

set -e

echo "=========================================="
echo "  Agent Harness Framework - Init Script"
echo "=========================================="
echo ""

# Check if this is a fresh project
if [ ! -f "memory/feature_list.json" ]; then
    echo "⚠️  No feature_list.json found."
    echo "   Run @Initializer first to set up the project."
    exit 1
fi

# Display progress
echo "📊 Current Progress:"
if command -v jq &> /dev/null; then
    TOTAL=$(jq '.features | length' memory/feature_list.json)
    PASSING=$(jq '[.features[] | select(.passes == true)] | length' memory/feature_list.json)
    echo "   Features: $PASSING / $TOTAL passing"
else
    TOTAL=$(grep -c '"passes"' memory/feature_list.json || echo "0")
    PASSING=$(grep -c '"passes": true' memory/feature_list.json || echo "0")
    echo "   Features: ~$PASSING / ~$TOTAL passing (install jq for accurate count)"
fi
echo ""

# Project-specific setup goes here
# Uncomment and customize based on your project type:

# --- Node.js Project ---
# if [ -f "package.json" ]; then
#     echo "📦 Installing Node.js dependencies..."
#     npm install
#     echo ""
#     echo "🚀 Starting development server..."
#     npm run dev &
#     echo "   Server starting at http://localhost:3000"
# fi

# --- Python Project ---
# if [ -f "requirements.txt" ]; then
#     echo "🐍 Installing Python dependencies..."
#     pip install -r requirements.txt
#     echo ""
#     echo "🚀 Starting application..."
#     python app.py &
# fi

# --- Docker Project ---
# if [ -f "docker-compose.yml" ]; then
#     echo "🐳 Starting Docker containers..."
#     docker-compose up -d
# fi

echo "✅ Init complete!"
echo ""
echo "Next steps:"
echo "  1. Use @Coder to implement features"
echo "  2. Check memory/claude-progress.md for context"
echo "  3. Run 'git log --oneline -10' to see recent changes"
